### ISSUE TITLE
How did you create the deb file

### ISSUE THREAD

**Issue by eredi93** [maxpowa/sophos-av-docker#1]
I'd love to use this image. but the last thing i wanna do is using a "random" version of Sophos coming from an unknown source.
https://github.com/maxpowa/sophos-av-docker/commit/b2469393ee0d7623dfe655c00295a595764352c5
where does the deb file comes from? did you build it or just found it on the internet?

**Comment by maxpowa** [comment]
Built it using mkinstpkg to avoid the regular installer which is an interactive cli and was sometimes making the build fail. Honestly you should be forking this package and building it (savinst) yourself if you're actually going to be using it.

**Comment by eredi93** [comment]
thanks for the reply @maxpowa 🙇 
i was trying the mkinstpkg but is making me pass an update server. could you by any chance share the command you used to build the deb package?

**Comment by maxpowa** [comment]
So unfortunately I didn't document this anywhere or anything... I did do a bit of digging though and found out through a combination of memory and trial-and-error, you can do `./mkinstpkg --sophos` to force it to use sophos' update server when generating the installer.

**Comment by eredi93** [comment]
That worked! thanks so much for sharing the command!
